### ISSUE TITLE
Aircrack-ng issues

### ISSUE THREAD

**Issue by nethunteros** [nethunteros/rpi3-kalimon#2]
From @vay3t on twitter:

- [x] Airodump works fine. but aireplay has problems with negative one. tested deauth attack
- [x] Specify a channel in airodump the message "fixed channel wlan0 -1"

Not sure if it's related or will help but I am using the more outdated repo from Nexmon (https://github.com/seemoo-lab/bcm-rpi3).

There newest repo is here: https://github.com/seemoo-lab/nexmon but had issues loading firmware on previous builds.  Will try to integrate the newer version.

**Comment by aagallag** [comment]
Rather than maintaining a fork of the legacy bcm-rpi3, I have been looking into adding cross-compile support to the nexmon repo.  I'm currently traveling for the holidays, and forgot to bring my RPi3 with me, so I haven't made any PRs as I can not test the changes.  But I do have compilation passing without errors.  If interested, you can see my change here: https://github.com/aagallag/nexmon/commit/6bbd8081cec581b93126d9beac0ea9168c3dee46

My plan for next week is to test my changes and submit a PR to seemoo-lab's nexmon repo.

If this seems like an acceptable approach to you, I can also submit a PR for this repo that uses your modified Kernel + the nexmon repo.

**Comment by codeinstein** [comment]
Use --ignore-negative-one on aireplay-ng to fix this.
Check 3:38 on this video I made: https://youtu.be/RZEZp8fqn_0

**Comment by nethunteros** [comment]
Aireplay-ng worked fine for me in testing with ignore-negative-one.  Airodump-ng also works fine for me.
